const LOCATIONS = {
  "Space Station": ["Commander", "Astronaut", "Flight Engineer", "Space Tourist", "Alien Researcher", "Roboticist", "Maintenance Specialist", "Payload Scientist"],
  "Pirate Ship": ["Captain", "First Mate", "Lookout", "Boatswain", "Cook", "Powder Monkey", "Prisoner", "Cabin Boy"],
  "Medieval Castle": ["King/Queen", "Knight", "Court Jester", "Blacksmith", "Royal Guard", "Maidservant", "Alchemist", "Dungeon Master"],
  "Hollywood Film Set": ["Director", "Lead Actor", "Stunt Double", "Makeup Artist", "Camera Operator", "Screenwriter", "Gaffer", "Craft Services"],
  "Luxury Cruise Ship": ["Ship Captain", "Cruise Director", "Casino Dealer", "Lifeguard", "Bartender", "Passenger", "Lounge Singer", "Head Chef"],
  "Jurassic Research Lab": ["Lead Geneticist", "Security Guard", "Dinosaur Handler", "Paleontologist", "Tour Guide", "Systems Programmer", "Lab Assistant", "Investor"],
  "Underground Coal Mine": ["Foreman", "Blasting Expert", "Geologist", "Safety Inspector", "Miner", "Cart Operator", "Canary Handler", "Union Representative"],
  "High School Prom": ["Principal", "Prom King/Queen", "DJ", "Chaperone", "Photographer", "Student", "Wallflower", "Limo Driver"],
  "Arctic Expedition Base": ["Expedition Leader", "Meteorologist", "Dog Sled Driver", "Wildlife Photographer", "Radio Operator", "Glaciologist", "Survivalist", "Physician"],
  "Ancient Egyptian Tomb": ["Lead Archaeologist", "Scribe", "Tourist", "Local Guide", "Thief", "Professor", "Photographer", "Excavator"],
  "Silicon Valley Startup": ["CEO", "Lead Developer", "UX Designer", "Venture Capitalist", "Marketing Intern", "DevOps Engineer", "Product Manager", "Office Manager"],
  "Grand Opera House": ["Conductor", "Prima Donna", "Stage Director", "Set Designer", "Lighting Technician", "Costume Designer", "Patron", "Understudy"],
  "Underwater Research Base": ["Base Commander", "Marine Biologist", "Submersible Pilot", "Dive Medic", "Sonar Technician", "Oceanographer", "Maintenance Diver", "Research Intern"],
  "Wild West Saloon": ["Saloon Owner", "Sheriff", "Outlaw", "Bartender", "Piano Player", "Card Shark", "Dance Hall Girl", "Bounty Hunter"],
  "International Airport": ["Pilot", "Air Traffic Controller", "Gate Agent", "Customs Officer", "Baggage Handler", "Passenger", "Security Officer", "Duty-Free Clerk"],
  "Volcano Research Station": ["Volcanologist", "Station Director", "Field Geologist", "Data Analyst", "Helicopter Pilot", "Seismologist", "Lab Technician", "Government Observer"],
  "Haunted Mansion": ["Ghost", "Paranormal Investigator", "Caretaker", "Séance Medium", "Skeptical Journalist", "Occult Historian", "Terrified Tourist", "Butler"],
  "Formula 1 Pit Lane": ["Race Car Driver", "Team Principal", "Pit Crew Chief", "Tire Specialist", "Aerodynamicist", "Race Strategist", "Sponsorship Rep", "Medical Officer"],
  "Antarctic Research Station": ["Station Commander", "Climate Scientist", "Penguin Researcher", "Chef", "Communications Officer", "Mechanical Engineer", "Psychologist", "Supply Pilot"],
  "Submarine": ["Captain", "Sonar Operator", "Torpedo Technician", "Navigator", "Chief Engineer", "Cook", "Medic", "Signals Intelligence Officer"],
  "Broadway Theater": ["Director", "Lead Actor", "Stage Manager", "Choreographer", "Box Office Manager", "Lighting Designer", "Props Master", "Understudy"],
  "Spy Agency Headquarters": ["Director of Operations", "Field Agent", "Cryptanalyst", "Tech Specialist", "Double Agent", "Recruiter", "Analyst", "Security Officer"],
  "Amazon Rainforest Camp": ["Lead Botanist", "Tribal Liaison", "Entomologist", "Camp Cook", "Jungle Guide", "Conservation Officer", "Herpetologist", "Documentary Filmmaker"],
  "Nuclear Power Plant": ["Plant Manager", "Nuclear Engineer", "Control Room Operator", "Safety Inspector", "Radiation Protection Technician", "Maintenance Worker", "Security Guard", "Government Regulator"],
  "Viking Longship": ["Jarl", "Shield-Maiden", "Navigator", "Skald", "Blacksmith", "Oarsman", "Prisoner", "Trader"],
  "Luxury Ski Resort": ["Ski Instructor", "Resort Manager", "Snowboard Champion", "Après-Ski Bartender", "Ski Patrol", "Gondola Operator", "Celebrity Guest", "Chalet Host"],
  "Military Boot Camp": ["Drill Sergeant", "Commanding Officer", "Medic", "Recruit", "Weapons Instructor", "Chaplain", "Cook", "JAG Officer"],
  "Tokyo Ramen Shop": ["Head Chef", "Apprentice Cook", "Waitress", "Regular Customer", "Food Critic", "Manager", "Delivery Driver", "Dishwasher"],
  "Tibetan Monastery": ["Head Lama", "Monk", "Novice", "Pilgrim", "Translator", "Mountain Guide", "Scholar", "Caretaker"],
  "Las Vegas Casino": ["Casino Manager", "Blackjack Dealer", "High Roller", "Security Chief", "Cocktail Waitress", "Card Counter", "Pit Boss", "Entertainment Coordinator"],
  "Safari Game Reserve": ["Game Warden", "Safari Guide", "Wildlife Photographer", "Poacher", "Veterinarian", "Tourist", "Conservation Researcher", "Camp Chef"],
  "Feudal Japanese Village": ["Samurai", "Daimyo", "Ninja", "Geisha", "Rice Farmer", "Merchant", "Monk", "Ronin"],
  "Deep Space Mining Colony": ["Colony Administrator", "Mining Foreman", "Asteroid Driller", "Shuttle Pilot", "Medical Officer", "Ore Processor", "Security Marshal", "Robot Technician"],
  "Mayan Temple Site": ["High Priest", "Archaeologist", "Local Shaman", "Tourist", "Site Excavator", "Epigrapher", "Temple Guardian", "Black Market Antiquities Dealer"],
  "Parisian Bakery": ["Master Baker", "Pastry Chef", "Shop Owner", "Apprentice", "Morning Regular", "Health Inspector", "Delivery Driver", "Flour Supplier"],
  "Stock Exchange Trading Floor": ["Floor Trader", "Exchange President", "Market Analyst", "Broker", "Regulator", "Algorithmic Trader", "Financial Journalist", "Intern"],
  "Arctic Oil Rig": ["Rig Manager", "Petroleum Engineer", "Roughneck", "Safety Officer", "Helicopter Pilot", "Cook", "Environmental Monitor", "Diver"],
  "Bavarian Beer Hall": ["Brewmaster", "Head Waitress", "Landlord", "Regular Patron", "Accordion Player", "Visiting Tourist", "Kitchen Chef", "Cellar Master"],
  "Cyberpunk Megacity": ["Corporate Executive", "Street Hacker", "Augmentation Surgeon", "Beat Cop", "Info Broker", "Smuggler", "Street Vendor", "Underground DJ"],
  "Nursing Home": ["Head Nurse", "Attending Physician", "Occupational Therapist", "Resident", "Social Worker", "Volunteer", "Activity Coordinator", "Dietary Aide"],
  "Artisan Cheese Factory": ["Head Cheesemaker", "Quality Inspector", "Cave Affineur", "Dairy Farmer", "Tour Guide", "Packaging Technician", "Sales Representative", "Apprentice"],
  "Ivy League University": ["President", "Tenured Professor", "Graduate Student", "Undergraduate", "Dean of Admissions", "Campus Security", "Librarian", "Endowment Manager"],
  "Ancient Roman Colosseum": ["Gladiator", "Emperor", "Lanista", "Senator", "Slave", "Bestiarius", "Arena Medic", "Spectator"],
  "Cruise Ship Kitchen": ["Executive Chef", "Sous Chef", "Pastry Cook", "Line Cook", "Kitchen Manager", "Health Inspector", "Dishwasher", "Food & Beverage Director"],
  "Tech Giant Campus": ["CEO", "Software Engineer", "HR Director", "Security Guard", "Cafeteria Worker", "Product Designer", "Lobbyist", "Janitor"],
  "Mafia Hideout": ["Don", "Consigliere", "Underboss", "Hitman", "Money Launderer", "Lookout", "Informant", "Hostage"],
  "Traveling Circus": ["Ringmaster", "Trapeze Artist", "Lion Tamer", "Clown", "Contortionist", "Ticket Seller", "Strongman", "Fortune Teller"],
  "Antarctic Ice Cave": ["Glaciologist", "Cave Explorer", "Photographer", "Safety Rope Handler", "Climate Researcher", "Base Camp Manager", "Ice Core Driller", "Survival Medic"],
  "Craft Brewery": ["Head Brewer", "Taproom Manager", "Yeast Scientist", "Keg Technician", "Hop Supplier", "Regular Customer", "Brewmaster Apprentice", "Marketing Director"],
  "Abandoned Space Shuttle": ["Salvage Engineer", "NASA Inspector", "Scrap Metal Dealer", "Historian", "Documentary Filmmaker", "Security Guard", "Aerospace Technician", "Urban Explorer"],
  "Himalayan Base Camp": ["Expedition Leader", "Sherpa Guide", "High-Altitude Medic", "Climber", "Weather Forecaster", "Logistics Coordinator", "Rescue Volunteer", "Journalist"],
  "Prohibition-Era Speakeasy": ["Club Owner", "Jazz Singer", "Bartender", "Bootlegger", "Undercover Detective", "Mob Enforcer", "Socialite", "Piano Player"],
  "Ancient Greek Agora": ["Philosopher", "Merchant", "City Official", "Sculptor", "Slave", "Hoplite Soldier", "Playwright", "Physician"],
  "Reality TV Show Set": ["Producer", "Show Host", "Contestant", "Camera Operator", "Psychologist", "Makeup Artist", "Network Executive", "Sound Technician"],
  "Vineyard and Winery": ["Vintner", "Sommelier", "Grape Picker", "Cellar Master", "Wine Critic", "Tour Guide", "Fermentation Scientist", "Estate Owner"],
  "Haunted Amusement Park": ["Park Owner", "Ride Operator", "Scare Actor", "Paranormal Investigator", "Maintenance Engineer", "Security Guard", "Ticket Taker", "Trapped Visitor"],
  "Country Club": ["Club President", "Golf Pro", "Caddy", "Tennis Coach", "Head Chef", "Bartender", "New Member", "Groundskeeper"],
  "Luxury Yacht": ["Owner", "Captain", "First Mate", "Chef", "Deckhand", "Dive Instructor", "Celebrity Guest", "Security Detail"],
  "Train Robbers' Gang": ["Gang Leader", "Safe Cracker", "Lookout", "Getaway Driver", "Insider Contact", "Horse Handler", "Disguise Expert", "Wounded Member"],
  "Deep Sea Fishing Boat": ["Captain", "First Mate", "Net Handler", "Sonar Operator", "Fish Processor", "Cook", "Marine Biologist Observer", "Deckie"],
  "Futuristic Smart City": ["City AI Administrator", "Traffic Algorithm Engineer", "Civil Rights Activist", "Urban Planner", "Drone Delivery Pilot", "Sustainability Officer", "Augmented Reality Guide", "Citizen"],
  "Upscale Hotel": ["General Manager", "Concierge", "Bellhop", "Housekeeping Staff", "Executive Chef", "VIP Guest", "Security Director", "Front Desk Clerk"],
  "Film Noir Detective Agency": ["Private Eye", "Femme Fatale", "Police Lieutenant", "Informant", "Corrupt Politician", "Secretary", "Crime Boss", "Witness"],
  "Organic Farm": ["Farm Owner", "Seasonal Harvester", "Soil Scientist", "Beekeeper", "Market Vendor", "Irrigation Specialist", "Volunteer Farmhand", "Agri-Inspector"],
  "Renaissance Fair": ["King", "Court Jester", "Blacksmith", "Jousting Knight", "Merchant", "Alchemist", "Fair Visitor", "Bard"],
  "Antarctic Whaling Station": ["Station Manager", "Harpoonist", "Marine Biologist", "Cook", "Mechanical Engineer", "Environmental Activist", "Dock Worker", "Fleet Captain"],
  "Hip Hop Recording Studio": ["Producer", "Rapper", "Sound Engineer", "A&R Executive", "Hype Man", "Backup Vocalist", "Beat Maker", "Studio Manager"],
  "Venetian Carnival": ["Masked Nobleman", "Street Performer", "Gondolier", "Mask Maker", "Tourist", "Merchant", "City Guard", "Courtesan"],
  "High-Security Prison": ["Warden", "Corrections Officer", "Inmate", "Prison Chaplain", "Parole Officer", "Criminal Lawyer", "Informant", "Prison Doctor"],
  "Mars Colony": ["Colony Governor", "Terraforming Engineer", "Geologist", "Medical Officer", "Life Support Technician", "Colonist Farmer", "Communications Officer", "Robot Supervisor"],
  "Medieval Siege": ["Siege Commander", "Catapult Engineer", "Foot Soldier", "Spy", "Field Physician", "Supply Master", "Herald", "Captured Enemy Knight"],
  "Tokyo Fish Market": ["Auctioneer", "Tuna Wholesaler", "Sushi Chef", "Delivery Driver", "Harbor Fisherman", "Food Safety Inspector", "Foreign Buyer", "Market Manager"],
  "Secret Underground Bunker": ["Bunker Commander", "Communications Expert", "Nuclear Physicist", "Political Advisor", "Security Detail", "Medical Officer", "Chef", "Civilian Survivor"],
  "Zombie Apocalypse Safe House": ["Group Leader", "Former Soldier", "Doctor", "Engineer", "Scout", "Trader", "Child Survivor", "Infected Newcomer"],
  "Fairy Tale Kingdom": ["Fairy Godmother", "Prince/Princess", "Dragon", "Enchanted Knight", "Village Elder", "Witch", "Talking Animal", "Woodcutter"],
  "Wall Street Hedge Fund": ["Fund Manager", "Quantitative Analyst", "Compliance Officer", "Trader", "Billionaire Investor", "Data Scientist", "Risk Manager", "Whistleblower"],
  "Gladiator Training School": ["Ludus Owner", "Lanista Trainer", "Champion Gladiator", "Rookie Fighter", "Physician", "Armorer", "Slave Manager", "Roman Patron"],
  "Offshore Tax Haven Island": ["Island Governor", "Wealth Manager", "Yacht Captain", "Money Launderer", "IRS Investigator", "Butler", "Crypto Broker", "Local Fisherman"],
  "Wizarding School": ["Headmaster", "Potions Professor", "Star Student", "Groundskeeper", "Dark Arts Instructor", "School Ghost", "Librarian", "First-Year Student"],
  "Neon Night Market": ["Market Organizer", "Street Food Chef", "Trinket Seller", "Pickpocket", "Tourist", "Local Teenager", "Performance Artist", "Security Guard"],
  "Artisan Pottery Studio": ["Master Potter", "Kiln Operator", "Glaze Chemist", "Art Student", "Gallery Owner", "Clay Supplier", "Workshop Instructor", "Intern"],
  "Espionage Safe House": ["Handler", "Field Agent", "Defector", "Communications Technician", "Forger", "Analyst", "Local Asset", "Extraction Specialist"],
  "Beachside Surf Camp": ["Head Surf Instructor", "Camp Director", "Lifeguard", "Beginner Student", "Competition Surfer", "Beach Vendor", "Marine Biologist", "Photographer"],
  "Antarctic Supply Ship": ["Ship Captain", "First Officer", "Cargo Master", "Marine Engineer", "Medic", "Cook", "Oceanographer", "Deck Hand"],
  "1920s Jazz Club": ["Club Owner", "Trumpet Player", "Singer", "Saxophonist", "Bartender", "Socialite", "Bouncer", "Undercover Cop"],
  "Abandoned Mental Asylum": ["Ghost", "Urban Explorer", "Paranormal Investigator", "Trespassing Teenager", "Security Guard", "Documentary Filmmaker", "Former Nurse", "Escaped Patient"],
  "Penguin Research Station": ["Station Director", "Ornithologist", "Field Technician", "Volunteer Researcher", "Wildlife Photographer", "Cook", "Veterinarian", "Weather Observer"],
  "Fashion Week Runway": ["Creative Director", "Supermodel", "Fashion Critic", "Wardrobe Stylist", "Photographer", "Boutique Buyer", "Makeup Artist", "Backstage Manager"],
  "Egyptian Bazaar": ["Merchant", "Haggling Buyer", "Pickpocket", "Carpet Dealer", "Spice Vendor", "Tourist Guide", "Snake Charmer", "Market Inspector"],
  "Ninja Clan Dojo": ["Grandmaster", "Senior Ninja", "Trainee", "Rival Clan Spy", "Weapon Forger", "Herbalist", "Clan Elder", "Messenger"],
  "Horse Racing Track": ["Jockey", "Trainer", "Track Owner", "Stable Hand", "Bookmaker", "Race Official", "Veterinarian", "Wealthy Bettor"],
  "Jungle Guerrilla Camp": ["Comandante", "Sniper", "Field Medic", "Radio Operator", "Scout", "Weapons Expert", "Embedded Journalist", "Defector"],
  "Artisanal Coffee Roastery": ["Head Roaster", "Green Coffee Buyer", "Barista Trainer", "Cupping Expert", "Cafe Manager", "Equipment Technician", "Regular Customer", "Delivery Driver"],
  "Mardi Gras Parade": ["Parade Marshal", "Float Designer", "Krewe Member", "Street Musician", "Bead Vendor", "Police Officer", "Tourist", "Local Resident"],
  "Genetic Research Institute": ["Lead Geneticist", "Lab Director", "Bioethicist", "Research Assistant", "Grant Auditor", "Bioinformatician", "Clinical Trial Coordinator", "Biosafety Officer"],
  "Renaissance Painting Workshop": ["Master Painter", "Guild Master", "Apprentice", "Wealthy Patron", "Pigment Merchant", "Model", "Art Critic", "Rival Artist"],
  "Ghost Town": ["Lone Drifter", "Local Historian", "Treasure Hunter", "Real Estate Speculator", "Photojournalist", "Squatter", "Ghost", "Sheriff's Spirit"],
  "Space Telescope Control Center": ["Mission Director", "Telescope Engineer", "Astrophysicist", "Data Scientist", "Communications Officer", "Night Shift Operator", "Visiting Journalist", "Software Developer"],
  "Underground Poker Room": ["House Dealer", "Room Operator", "Card Shark", "High-Stakes Player", "Loan Shark", "Waitress", "Undercover Detective", "Chip Counter"],
  "Zoo": ["Zookeeper", "Zoo Director", "Veterinarian", "Animal Trainer", "Visitor", "Biologist", "Maintenance Worker", "Gift Shop Attendant"],
  "Titanic": ["Ship Captain", "First-Class Passenger", "Steerage Passenger", "Chief Engineer", "Wireless Operator", "Steward", "Lookout", "Ship's Doctor"],
  "Rainforest Eco-Lodge": ["Lodge Manager", "Nature Guide", "Bird Watcher", "Ecotourist", "Local Indigenous Guide", "Conservation Biologist", "Chef", "Kayak Instructor"],
  "Quantum Computing Lab": ["Principal Researcher", "Quantum Engineer", "Cryogenics Technician", "Software Developer", "Lab Manager", "Physics Professor", "Government Liaison", "Grad Student"],
  "Wild Animal Sanctuary": ["Sanctuary Director", "Animal Rehabilitator", "Veterinarian", "Volunteer", "Donor Representative", "Wildlife Photographer", "Education Officer", "Night Keeper"],
  "Private Island Resort": ["Island Owner", "Resort Manager", "Water Sports Instructor", "Personal Chef", "Security Chief", "Celebrity Guest", "Helicopter Pilot", "Masseuse"],
  "Cargo Ship": ["Captain", "Chief Officer", "Port Agent", "Customs Inspector", "Engine Room Chief", "Able Seaman", "Cook", "Stowaway"],
  "Alien Embassy": ["Ambassador", "Translator", "Xenobiologist", "Security Attaché", "Cultural Liaison", "Earth Representative", "Alien Dignitary", "Journalist"],
  "Auction House": ["Auctioneer", "House Director", "Consignor", "Bidder", "Art Appraiser", "Insurance Agent", "Security Guard", "Catalog Writer"],
  "Viking Mead Hall": ["Chieftain", "Skald", "Shield-Maiden", "Trader", "Thrall", "Weapons Master", "Feast Organizer", "Wandering Bard"],
  "Underwater Shipwreck": ["Dive Leader", "Marine Archaeologist", "Salvage Diver", "Underwater Photographer", "Decompression Specialist", "Treasure Hunter", "Research Historian", "Safety Diver"],
  "Luxury Spa Retreat": ["Spa Director", "Massage Therapist", "Yoga Instructor", "Nutritionist", "Celebrity Client", "Aesthetician", "Receptionist", "Fitness Coach"],
  "Moonshine Distillery": ["Master Distiller", "Revenue Agent", "Still Operator", "Delivery Runner", "Local Distributor", "Grain Supplier", "Taster", "Lookout"],
  "Archaeological Dig Site": ["Lead Archaeologist", "Stratigraphic Analyst", "Field Excavator", "Conservator", "Site Photographer", "University Professor", "Local Labor Coordinator", "Government Liaison"],
  "Pirate Cove": ["Pirate Captain", "Quartermaster", "Navigator", "Treasure Keeper", "Cannoneer", "Lookout", "Prisoner", "Ship's Surgeon"],
  "Public Library": ["Head Librarian", "Reference Archivist", "Children's Program Coordinator", "Regular Patron", "IT Specialist", "Security Guard", "Book Restorer", "Volunteer"],
  "Avalanche Research Center": ["Research Director", "Snow Scientist", "Forecaster", "Rescue Team Leader", "Field Surveyor", "Explosives Technician", "Mountain Guide", "Data Analyst"],
  "Fire Station": ["Fire Chief", "Lieutenant", "Firefighter", "Paramedic", "Dispatcher", "Arson Investigator", "Rookie", "Mechanic"],
  "Royal Court": ["Monarch", "Prime Minister", "Court Advisor", "Royal Guard", "Ambassador", "Jester", "Lady-in-Waiting", "Spy"],
  "Dragon's Lair": ["Dragon", "Knight", "Sorcerer", "Treasure Thief", "Princess/Prince", "Adventurer", "Dwarf Miner", "Dragon Tamer"],
  "Refugee Camp": ["Camp Administrator", "Aid Worker", "Doctor", "Interpreter", "Journalist", "Refugee Family", "UN Representative", "Security Officer"],
  "Country Music Recording Studio": ["Producer", "Lead Singer", "Steel Guitar Player", "Session Musician", "A&R Manager", "Sound Engineer", "Label Executive", "Manager"],
  "Luxury Train": ["Train Conductor", "Sleeping Car Attendant", "Executive Chef", "Mystery Author", "Wealthy Passenger", "Security Officer", "Sommelier", "Porter"],
  "Superhero HQ": ["Team Leader", "Gadget Engineer", "Rookie Hero", "Intelligence Analyst", "Medical Officer", "Public Relations Manager", "Villain Informant", "Veteran Hero"],
  "Feudal European Manor": ["Lord/Lady", "Steward", "Peasant Farmer", "Knight", "Blacksmith", "Scribe", "Tax Collector", "Wandering Priest"],
  "Fashion Design Studio": ["Head Designer", "Pattern Maker", "Fabric Buyer", "Seamstress", "Brand Manager", "Fashion Blogger", "Intern", "Model"],
  "Tropical Volcano Island": ["Volcanologist", "Island Chief", "Tourist", "Marine Biologist", "Helicopter Rescue Pilot", "Local Fisherman", "Geologist", "Emergency Manager"],
  "Comic Book Convention": ["Convention Organizer", "Celebrity Guest", "Superfan", "Cosplayer", "Comic Book Artist", "Security Guard", "Vendor", "Journalist"],
  "Abandoned Factory": ["Urban Explorer", "Security Guard", "Graffiti Artist", "Film Director", "Environmental Inspector", "Squatter", "Paranormal Investigator", "Real Estate Developer"],
  "Mars Research Rover Mission": ["Mission Commander", "Rover Pilot", "Geologist", "Astrobiologist", "Communications Engineer", "Field Medic", "NASA Liaison", "Data Analyst"],
  "Samurai Dojo": ["Master Sensei", "Senior Student", "Junior Disciple", "Ronin Challenger", "Dojo Administrator", "Weapons Craftsman", "Feudal Lord Patron", "Spy"],
  "High-End Restaurant Kitchen": ["Executive Chef", "Sous Chef", "Pastry Chef", "Sommelier", "Line Cook", "Health Inspector", "Food Critic", "Dishwasher"],
  "Internet Troll Farm": ["Operations Manager", "Content Writer", "Account Manager", "Analyst", "Tech Developer", "Recruiter", "Investigative Reporter", "Cybersecurity Agent"],
  "Rock Band Tour Bus": ["Lead Singer", "Guitar Tech", "Tour Manager", "Bus Driver", "Sound Engineer", "Groupie", "Journalist", "Bodyguard"],
  "Pirate Radio Station": ["DJ", "Station Owner", "Sound Engineer", "Volunteer Broadcaster", "FCC Agent", "Advertiser", "Listener Call-In Fan", "Antenna Technician"],
  "Deep Jungle Research Camp": ["Camp Director", "Primatologist", "Field Botanist", "Entomologist", "Local Tribal Guide", "Camp Cook", "Medical Officer", "Drone Operator"],
  "Wedding Venue": ["Event Coordinator", "Bride/Groom", "Officiant", "Caterer", "Photographer", "Florist", "DJ", "Uninvited Guest"],
  "Cold War Soviet Embassy": ["Ambassador", "KGB Officer", "Cipher Clerk", "Cultural Attaché", "CIA Plant", "Diplomatic Courier", "Cook", "Bodyguard"],
  "1950s Diner": ["Owner", "Head Cook", "Car Hop", "Soda Jerk", "Regular", "Health Inspector", "Jukebox Repairman", "Teenage Patron"],
  "Interstellar Trading Post": ["Station Commander", "Alien Merchant", "Human Trader", "Customs Officer", "Smuggler", "Bounty Hunter", "Translator", "Maintenance Drone Operator"],
  "Dragon Boat Race": ["Team Captain", "Drummer", "Paddler", "Steersman", "Race Official", "Coach", "Spectator", "Festival Organizer"],
  "Medieval Apothecary": ["Master Apothecary", "Herbalist", "Apprentice", "Witch Doctor", "Merchant Customer", "Inquisitor", "Alchemist", "Plague Doctor"],
  "Skyscraper Construction Site": ["Site Foreman", "Structural Engineer", "Safety Inspector", "Steel Worker", "Crane Operator", "Architect", "Electrician", "Project Manager"],
  "Auction Barn": ["Auctioneer", "Livestock Farmer", "Cattle Buyer", "Ranch Hand", "Veterinarian", "Bank Loan Officer", "Local Rancher", "Reporter"],
  "Space Elevator Terminal": ["Terminal Director", "Elevator Operator", "Cargo Manager", "Orbital Engineer", "Passenger", "Customs Agent", "Maintenance Technician", "Security Officer"],
  "Spy Satellite Control Room": ["Intelligence Director", "Satellite Operator", "Image Analyst", "Signals Engineer", "Cybersecurity Officer", "Liaison Officer", "Legal Advisor", "Maintenance Tech"],
  "Underworld Fight Club": ["Promoter", "Champion Fighter", "Corner Man", "Bookie", "Ring Doctor", "Undercover Cop", "Bettor", "Towel Boy"],
  "Olympic Village": ["Team Coach", "Star Athlete", "Team Doctor", "Olympic Committee Official", "Sports Journalist", "Anti-Doping Officer", "Volunteer", "Sponsor Representative"],
  "Eco-Protest Camp": ["Campaign Leader", "Environmental Lawyer", "Volunteer Protester", "Journalist", "Undercover Officer", "Drone Pilot", "Social Media Manager", "Local Resident"],
  "World War II U-Boat": ["Kapitän", "First Watch Officer", "Torpedo Mechanic", "Radio Operator", "Navigator", "Chief Engineer", "Cook", "Interpreter"],
  "Fairy Ring Forest": ["Fairy Queen", "Woodland Elf", "Human Wanderer", "Druid", "Gnome Herbalist", "Cursed Knight", "Forest Spirit", "Sprite Trickster"],
  "Biotech Startup": ["CEO", "Lead Researcher", "IP Lawyer", "Lab Technician", "Clinical Trial Coordinator", "Venture Capitalist", "Regulatory Affairs Officer", "Marketing Lead"],
  "Nuclear Submarine": ["Commanding Officer", "Weapons Officer", "Reactor Engineer", "Sonar Technician", "Navigator", "Medical Officer", "Cook", "Intelligence Officer"],
  "Rural American Diner": ["Owner-Cook", "Waitress", "Regular Farmer", "Truck Driver", "Passing Traveler", "County Sheriff", "Local Gossip", "Health Inspector"],
  "Deep Ocean Trench Expedition": ["Expedition Leader", "Submersible Pilot", "Marine Biologist", "Geologist", "Remotely Operated Vehicle Operator", "Oceanographer", "Ship Captain", "Documentary Filmmaker"],
  "Luxury Auction Gala": ["Auction House CEO", "Celebrity Bidder", "Art Appraiser", "Security Director", "Event Planner", "Press Journalist", "Philanthropist Donor", "Caterer"],
  "Victorian London": ["Inspector", "Street Urchin", "Surgeon", "Factory Owner", "Governess", "Chimney Sweep", "Dockworker", "Aristocrat"],
  "Culinary School": ["Executive Chef-Instructor", "Culinary Dean", "First-Year Student", "Pastry Arts Student", "Kitchen Manager", "External Examiner", "Equipment Supplier", "Food Critic Visitor"],
  "Illegal Arms Market": ["Weapons Dealer", "Mercenary Buyer", "Undercover Interpol Agent", "Smuggler", "Arms Broker", "Warlord Representative", "Corrupt Official", "Courier"],
  "Ice Hotel": ["Hotel Manager", "Ice Sculptor", "Reindeer Sled Driver", "Winter Tourist", "Concierge", "Northern Lights Guide", "Chef", "Security Guard"],
  "Space Pirate Ship": ["Pirate Captain", "Navigator", "Weapons Officer", "Engineer", "Captured Merchant", "Crew Recruit", "AI Ship Intelligence", "Medical Officer"],
  "Crocodile Farm": ["Farm Owner", "Crocodile Handler", "Veterinarian", "Tour Guide", "Leather Goods Buyer", "Safety Officer", "Feed Technician", "Researcher"],
  "Chernobyl Exclusion Zone": ["Radiation Safety Officer", "Liquidator Veteran", "Urban Explorer", "Dosimetrist", "Archaeologist of Abandonment", "Government Monitor", "Journalist", "Wildlife Biologist"],
  "Tech Incubator": ["Managing Director", "Startup Founder", "Mentor Investor", "Legal Advisor", "Marketing Consultant", "Resident Engineer", "Community Manager", "Failed Entrepreneur"],
  "Ancient Chinese Imperial Court": ["Emperor/Empress", "Chief Eunuch", "Military General", "Court Scholar", "Imperial Guard", "Concubine", "Court Physician", "Rival Prince"],
  "North Korean Defector Escape Route": ["Defector", "Underground Guide", "Border Guard", "NGO Worker", "Chinese Police Officer", "Broker Smuggler", "Translator", "Safe House Host"],
  "Luxury Watchmaker's Atelier": ["Master Watchmaker", "Apprentice", "Gem Setter", "Brand Director", "Watch Critic", "Wealthy Client", "Parts Supplier", "Quality Inspector"],
  "Doomsday Prepper Bunker": ["Bunker Owner", "Survival Trainer", "Medical Prepper", "Security Guard", "Food Storage Manager", "Ham Radio Operator", "Engineer", "Skeptical Family Member"],
  "Smuggler's Tunnel": ["Tunnel Operator", "Cartel Enforcer", "Customs Agent", "Mule", "Tunnel Engineer", "Lookout", "Bribed Official", "Journalist"],
  "Street Art Festival": ["Festival Director", "Muralist", "Graffiti Artist", "Local Business Owner", "City Official", "Art Critic", "Spray Can Supplier", "Photographer"],
  "WWII Resistance Cell": ["Cell Leader", "Radio Operator", "Forger", "Courier", "Collaborator Infiltrator", "Local Safehouse Host", "Weapons Smuggler", "Downed Allied Pilot"],
  "Virtual Reality Game World": ["Game Master", "Pro Gamer", "NPC Character", "Developer Tester", "Glitched Entity", "In-World Merchant", "Player Avatar", "Server Administrator"],
  "Food Truck Festival": ["Festival Organizer", "Food Truck Chef", "Regular Customer", "Health Inspector", "Social Media Influencer", "Local Radio Host", "Volunteer", "Competing Vendor"],
  "Inca Ruins": ["Archaeologist", "Peruvian Government Official", "Tourist", "Local Guide", "Treasure Hunter", "Restoration Expert", "Journalist", "University Professor"],
  "Medieval Plague Hospital": ["Plague Doctor", "Apothecary", "Gravedigger", "Nun Nurse", "Dying Noble", "Accused Witch", "City Official", "Flagellant Penitent"],
  "Skydiving School": ["Jump Master", "Tandem Instructor", "First-Time Student", "Experienced Solo Jumper", "Packer", "Videographer", "Safety Officer", "Pilot"],
  "Coastal Lighthouse": ["Lighthouse Keeper", "Assistant Keeper", "Maritime Historian", "Stranded Sailor", "Fog Horn Mechanic", "Journalist", "Coast Guard Officer", "Ghost"],
  "Wild West Sheriff's Office": ["Sheriff", "Deputy", "Prisoner", "Bounty Hunter", "Outlaw Informant", "Town Mayor", "Circuit Judge", "Newspaper Reporter"],
  "Fantasy Tavern": ["Innkeeper", "Bard", "Mercenary", "Elven Ranger", "Dwarf Merchant", "Mysterious Hooded Stranger", "Town Drunk", "Serving Wench"],
  "Bioweapons Research Facility": ["Lead Virologist", "Biosafety Level 4 Technician", "Military Liaison", "Ethics Officer", "Security Director", "Lab Manager", "Whistleblower", "Government Inspector"],
  "Medieval Tournament": ["Tournament Marshal", "Champion Knight", "Challenger Knight", "Royal Patron", "Armorer", "Herald", "Merchant Vendor", "Crowd Spectator"],
  "Wildlife Documentary Crew": ["Director", "Camera Operator", "Sound Recordist", "Wildlife Presenter", "Field Biologist", "Drone Pilot", "Local Tracker", "Narrative Producer"],
  "Newspaper Headquarters": ["Editor-in-Chief", "Investigative Reporter", "Photojournalist", "Copy Editor", "Whistleblower Source", "Legal Counsel", "Sales Manager", "Printer"],
  "Medieval Herbalist's Cottage": ["Wise Woman", "Apprentice Herbalist", "Village Elder", "Sick Peasant", "Suspicious Inquisitor", "Traveling Merchant", "Midwife", "Gathering Child"],
  "Prison Break Tunnel": ["Escape Mastermind", "Tunnel Digger", "Guard Briber", "Lookout", "Distraction Specialist", "Outside Contact", "Reluctant Inmate", "Rat Informant"],
  "Coral Reef Research Station": ["Station Director", "Coral Biologist", "Dive Master", "Water Quality Chemist", "Marine Photographer", "Research Intern", "Boat Captain", "Climate Scientist"],
  "Robot Factory": ["Factory Director", "Robotics Engineer", "Assembly Line Worker", "Quality Control Inspector", "AI Programmer", "Safety Officer", "Union Representative", "Corporate Spy"],
  "Black Market Art Gallery": ["Gallery Owner", "Forger", "Wealthy Collector", "Art Authenticator", "Undercover Agent", "Smuggler", "Museum Curator Turned Criminal", "Fixer"],
  "Ancient Library of Alexandria": ["Chief Librarian", "Scrolls Curator", "Greek Scholar", "Egyptian Priest", "Roman Soldier", "Visiting Philosopher", "Scribe", "Fire Investigator"],
  "Art Heist": ["Mastermind", "Tech Expert", "Inside Contact", "Driver", "Lookout", "Art Appraiser", "Security Guard", "Insurance Investigator"],
  "Gold Rush Mining Town": ["Claim Owner", "Assayer", "Saloon Keeper", "Prospector", "Supply Merchant", "Bandit", "Sheriff", "Traveling Doctor"],
  "Amazon River Expedition": ["Expedition Leader", "River Guide", "Zoologist", "Anthropologist", "Boat Engineer", "Photographer", "Tribal Elder Contact", "Medic"],
  "Emergency Room": ["Attending Physician", "Head Nurse", "Surgeon", "Paramedic", "Triage Nurse", "Resident", "Hospital Administrator", "Anxious Family Member"],
  "Polar Bear Research Camp": ["Research Lead", "Biologist", "Helicopter Pilot", "Bear Tracker", "Camp Cook", "Climate Scientist", "Wildlife Photographer", "Veterinarian"],
  "Moonbase": ["Base Commander", "Geologist", "Habitat Engineer", "Medic", "Comms Officer", "Botanist (Lunar Agriculture)", "Robot Operator", "Supply Shuttle Pilot"],
  "Underground Hacker Den": ["Lead Hacker", "Network Intrusion Specialist", "Cryptocurrency Broker", "FBI Agent", "Script Kiddie", "Social Engineer", "Dark Web Merchant", "System Administrator"],
  "Traditional Sumo Wrestling Stable": ["Stable Master", "Champion Wrestler", "Apprentice Rikishi", "Stable Cook", "Sumo Association Official", "Sports Journalist", "Equipment Manager", "Senior Wrestler"],
  "Whitewater Rafting Outpost": ["Lead Guide", "Safety Kayaker", "Rafting Instructor", "First-Time Rafter", "Camp Manager", "Gear Technician", "Wilderness Medic", "Photographer"],
  "Antarctic Ice Core Laboratory": ["Lab Director", "Glaciologist", "Climate Historian", "Core Driller", "Data Analyst", "Equipment Technician", "Visiting Scientist", "Station Chef"],
  "Medieval Dungeon": ["Dungeon Master", "Torturer", "Prisoner of War", "Royal Inquisitor", "Jailer", "Sentenced Criminal", "Rescue Attempt Knight", "Prison Chaplain"],
  "Luxury Car Showroom": ["Showroom Manager", "Sales Representative", "Master Mechanic", "Wealthy Customer", "Car Journalist", "Finance Manager", "Brand Ambassador", "Detailer"],
  "Rooftop Beekeeping Collective": ["Head Beekeeper", "Honey Harvester", "Queen Bee Specialist", "Wax Processor", "Urban Agriculture Officer", "Volunteer Beekeeper", "Honey Distributor", "Entomologist"],
  "Post-Apocalyptic Wasteland Outpost": ["Warlord", "Scavenger", "Medic", "Water Purification Engineer", "Trader", "Scout", "Mechanic", "Refugee"],
  "Witch Trial Court": ["Judge", "Accused Witch", "Prosecutor", "Defense Counsel", "Witness", "Town Minister", "Constable", "Spectator"],
  "Virtual Reality Arcade": ["Arcade Owner", "VR Game Designer", "Regular Gamer", "Tournament Player", "Technical Support", "Cashier", "Birthday Party Group", "Journalist"],
  "Luxury Train Heist": ["Heist Leader", "Safe Cracker", "Inside Steward", "Train Guard", "Disguised Passenger", "Lookout", "Getaway Planner", "Hostage"],
  "Shark Research Vessel": ["Lead Marine Biologist", "Shark Tagger", "Underwater Videographer", "Boat Captain", "Data Recorder", "Shark Cage Diver", "Safety Officer", "Documentary Producer"],
  "Political Campaign Headquarters": ["Campaign Manager", "Candidate", "Speech Writer", "Pollster", "Volunteer Coordinator", "Media Strategist", "Opposition Research Analyst", "Donor"],
  "Extreme Caving Expedition": ["Lead Spelunker", "Rope Specialist", "Geologist", "Medic", "Cartographer", "Photographer", "Safety Observer", "Rescue Team Standby"],
  "Antarctic Drone Test Site": ["Program Director", "Drone Engineer", "Test Pilot", "Data Scientist", "Meteorologist", "Equipment Technician", "Safety Monitor", "Military Observer"],
  "Secret Garden Party": ["Host", "Head Gardener", "Caterer", "Jazz Musician", "Celebrity Guest", "Gossip Columnist", "Sommelier", "Paparazzi"],
  "Cryptid Research Expedition": ["Expedition Leader", "Cryptozoologist", "Wilderness Tracker", "Documentary Director", "Local Eyewitness", "Skeptic Scientist", "Photographer", "Survivalist Guide"],
  "Gladiatorial Arena": ["Arena Director", "Champion Gladiator", "Rookie Gladiator", "Weapons Master", "Medic", "Betting Handler", "Emperor's Representative", "Mob Handler"],
  "Space Debris Cleanup Crew": ["Mission Commander", "Debris Net Operator", "Orbital Mechanic", "Mission Planner", "Astronaut Pilot", "Remote Systems Operator", "Safety Officer", "Government Inspector"],
  "Noodle Bar (Hong Kong Style)": ["Head Chef", "Wonton Wrapper", "Floor Manager", "Regular Customer", "Delivery Rider", "Health Inspector", "Dishwasher", "Late-Night Drunk"],
  "Experimental Aircraft Testing Facility": ["Test Pilot", "Chief Engineer", "Aerodynamics Specialist", "Safety Monitor", "Data Recorder", "Government Inspector", "Corporate Executive", "Ground Crew Chief"],
  "Warlord's Compound": ["Warlord", "Second-in-Command", "Arms Dealer", "Child Soldier", "Hostage", "Field Commander", "Embedded Journalist", "Defector"],
  "Steampunk Airship": ["Captain", "Chief Engineer", "Navigator", "Stoker", "Passenger", "Smuggler", "Airship Mechanic", "Sky Pirate Stowaway"],
  "Cat Cafe": ["Cafe Owner", "Barista", "Cat Caretaker", "Regular Customer", "Veterinarian", "Cat Adoption Representative", "Social Media Influencer", "Visiting Tourist"],
  "Crypto Mining Farm": ["Farm Owner", "Systems Administrator", "Cooling Engineer", "Investor", "Security Guard", "Electrician", "Blockchain Developer", "Power Company Inspector"],
  "Illegal Dumping Site": ["Waste Disposal Operator", "Environmental Inspector", "Crime Scene Investigator", "Whistleblower", "Truck Driver", "Local Activist", "Corporate Lawyer", "Journalist"],
  "Antarctic Meteorite Hunt": ["Expedition Geologist", "Meteorite Hunter", "Camp Medic", "Snowmobile Driver", "Station Coordinator", "Planetary Scientist", "Photographer", "Logistics Officer"],
  "Swamp Bayou": ["Trapper", "Gator Hunter", "Voodoo Priestess", "Game Warden", "Lost Tourist", "Cajun Cook", "Smuggler", "Herpetologist"],
  "Upscale Dog Show": ["Show Organizer", "Champion Dog Handler", "Dog Breeder", "Veterinarian", "Judge", "Nervous Competitor", "Groomer", "Kennel Club Official"],
  "International Space Race Command": ["Space Agency Director", "Rocket Engineer", "Astronaut", "Mission Controller", "Government Minister", "Press Officer", "Rival Agency Spy", "Software Developer"],
  "Prehistoric Mammoth Hunt": ["Tribe Leader", "Lead Hunter", "Shaman", "Scout", "Tool Maker", "Elder", "Young Warrior", "Injured Hunter"],
  "Drug Cartel Compound": ["Cartel Boss", "Lieutenant", "Chemist", "Enforcer", "Money Counter", "Lookout", "Hostage", "DEA Undercover Agent"],
  "Giant Squid Research Vessel": ["Marine Biologist", "Vessel Captain", "Underwater Camera Operator", "Sonar Technician", "Deep Sea Ecologist", "Crew Member", "Documentary Producer", "Research Assistant"],
  "Luxury Penthouse Party": ["Host Billionaire", "Socialite Guest", "DJ", "Personal Security", "Caterer", "Celebrity Attendee", "Tabloid Reporter", "Mysterious Uninvited Guest"],
  "Outback Cattle Drive": ["Head Drover", "Station Owner", "Stockman", "Cook", "Vet", "Jackaroo", "Aboriginal Tracker", "Mustering Helicopter Pilot"],
  "Futuristic Prison": ["Warden AI", "Human Corrections Officer", "Hacker Inmate", "Prison Psychologist", "Political Prisoner", "Augmented Criminal", "Maintenance Tech", "Visitor"],
  "Coral Triangle Dive Expedition": ["Dive Master", "Marine Biologist", "Underwater Photographer", "Conservation Officer", "Boat Captain", "Reef Monitor", "Eco-Tour Guest", "Local Fisher"],
  "Indie Game Development Studio": ["Creative Director", "Lead Programmer", "Artist", "Sound Designer", "QA Tester", "Narrative Writer", "Community Manager", "Publisher Rep"],
  "Colonial Trading Post": ["Company Governor", "Merchant", "Fur Trapper", "Indigenous Trader", "Soldier", "Missionary", "Ship Captain", "Indentured Servant"],
  "World Chess Championship": ["Tournament Director", "Grandmaster Challenger", "Reigning Champion", "Second (Second Player's Coach)", "FIDE Arbiter", "Press Officer", "Commentator", "Suspicious Spectator"],
  "Flooded City": ["Emergency Coordinator", "Boat Rescue Driver", "Stranded Resident", "Relief Aid Worker", "Journalist", "National Guard Soldier", "Looter", "Engineer"],
  "Abandoned Theme Park": ["Urban Explorer", "Security Guard", "Documentary Filmmaker", "Historian", "Graffiti Artist", "Paranormal Investigator", "Former Ride Operator", "Real Estate Developer"],
  "Extreme Couponing Store": ["Store Manager", "Coupon Enthusiast", "Checkout Cashier", "Coupon Fraud Investigator", "Regular Shopper", "Store Supervisor", "Manufacturer Rep", "Suspicious Regular"],
  "Elite Hacker Competition (CTF)": ["Competition Organizer", "Elite Hacker", "Corporate Sponsor", "Government Recruiter", "Team Captain", "First-Time Competitor", "Security Researcher", "Referee"],
  "Polar Ice Cap": ["Arctic Researcher", "Polar Bear Biologist", "Climate Activist", "Expedition Guide", "Photographer", "Icebreaker Ship Captain", "Indigenous Hunter", "Drone Operator"],
  "Lost City of Gold (El Dorado)": ["Conquistador", "Indigenous Chief", "Treasure Hunter", "Archaeologist", "Mercenary Guide", "Jungle Shaman", "Documentary Director", "Cartographer"],
  "Offshore Wind Farm": ["Farm Manager", "Wind Turbine Engineer", "Marine Safety Officer", "Helicopter Transfer Pilot", "Environmental Monitor", "Maintenance Technician", "Grid Controller", "Government Inspector"],
  "Satanic Panic Town (1980s)": ["Evangelist Pastor", "Accused Babysitter", "Town Sheriff", "Concerned Parent", "Skeptical Psychologist", "Tabloid Reporter", "Defense Lawyer", "Teenager"],
  "Underground Flower Market": ["Market Manager", "Rose Supplier", "Florist Buyer", "Street Vendor", "Customs Officer", "Illegal Orchid Trader", "Botanical Inspector", "Delivery Driver"],
  "Alien Abduction Site": ["UFO Researcher", "Alleged Abductee", "Government MIB Agent", "Skeptic Scientist", "Journalist", "Conspiracy Theorist", "Alien Entity", "Local Sheriff"],
  "Antique Roadshow": ["Show Host", "Antique Appraiser", "Hopeful Seller", "Fake Item Spotter", "Camera Crew", "Provenance Researcher", "Auction House Representative", "Expert Restorer"],
  "Ski Jump Competition": ["Head Coach", "Champion Jumper", "Rookie Competitor", "Judge", "Hill Safety Officer", "Sports Commentator", "Equipment Technician", "Ski Federation Official"],
  "Jellyfish Research Platform": ["Lead Biologist", "Platform Captain", "ROV Operator", "Water Sampling Technician", "Toxicologist", "Data Analyst", "Visiting Scientist", "Safety Officer"],
  "Ancient Colosseum Backstage": ["Gladiator Trainer", "Beast Handler", "Injured Gladiator", "Emperor's Steward", "Weapon Keeper", "Arena Doctor", "Slave Manager", "Propaganda Writer"],
  "Deep Cave Brewery": ["Master Brewer", "Cave Keeper", "Fermentation Scientist", "Tour Guide", "Tasting Room Host", "Barrel Cooper", "Water Source Monitor", "Distributor"],
  "Iceberg Tourist Cruise": ["Cruise Captain", "Glaciologist Guide", "Passenger", "Safety Officer", "Whale Watch Specialist", "Photographer", "First Mate", "Eco-Tourism Director"]
};
